spring:
  application:
    name: ship-o-hoi
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=ship_o_hoi_dev;encrypt=false;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: ${datasource.username}
    password: ${datasource.password}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    baseline-on-migrate: true
    baseline-version: 1
tracking:
  mmsi-watchlist:
    - "304011027"  # THESEUS - General Cargo, IMO 9199256
    - "314551000"  # WILSON HERON - General Cargo, IMO 9116022

aisstream:
  api-key: ${aisstream.api-key}
destinations:
  active: Engebø
  profiles:
    - name: Engebø
      aliases:
        - engebo
        - engebo hamn
        - engebo kai
        - engebohavn
        - engebo havn
        - nofde
      latitude: 61.487982
      longitude: 5.442754
    - name: Haugesund
      aliases:
        - haugesund
        - haugesund hamn
        - haugesund kai
        - haugesundhavn
        - haugesund havn
        - hauges
      latitude: 59.4138
      longitude: 5.2677
    - name: Fuzhou
      aliases:
        - fuzhou
        - cnfuz
        - cn fuz
        - cn fzg
        - mawei
        - foochow
      latitude: 26.015
      longitude: 119.480
    - name: Durban
      aliases:
        - durban
        - za dur
        - zadur
        - dbn
      latitude: -29.8622
      longitude: 31.0297
    - name: Barentsburg
      aliases:
        - barentsburg
        - barentsburg hamn
        - barentsburg kai
        - barentsburghavn
        - barentsburg havn
        - barentsb
      latitude: 78.0667
      longitude: 14.2333
barentswatch:
  auth:
    token-url: https://id.barentswatch.no/connect/token
    client-id: ${barentswatch.client-id}
    client-secret: ${barentswatch.client-secret}
    scope: ais
logging:
  level:
    no.hauglum.ship_o_hoi: INFO
